### ISSUE TITLE
Exclude certain tables option

### ISSUE THREAD

**Issue by ziming** [digifactory/laravel-pull-production-data#14] opened 2020-01-23 14:04 UTC
Hi,

Nice package out there. Would be great if I can specify to exclude certain huge tables. Where in local development I have a smaller subset

**Comment by m-bosch** [comment] 2021-04-24 09:16
Hi Ziming, 

interesting, only our current workflow is to delete the local tables first, so when we wont import these they will be missing.

What would you prefer as expected behaviour?

If you want you can also make a PR for it.

**Comment by m-bosch** [comment] 2022-08-29 09:41
@ziming can we still help you with this? maybe together with #29 we could solve the issue?

**Comment by m-bosch** [comment] 2024-12-29 15:44
We close this issue, because of no active replies from @ziming

**Closed as completed by m-bosch** 2024-12-29 15:44 UTC
Labels: enhancement
